/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frameDetect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5e570e9a700c7060347c1b1cf0883bdd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/loraJam/frameDetect.h>
// pydoc.h is automatically generated in the build directory
#include <frameDetect_pydoc.h>

void bind_frameDetect(py::module& m)
{

    using frameDetect    = gr::loraJam::frameDetect;


    py::class_<frameDetect, gr::block, gr::basic_block,
        std::shared_ptr<frameDetect>>(m, "frameDetect", D(frameDetect))

        .def(py::init(&frameDetect::make),
           D(frameDetect,make)
        )
        



        ;




}








