/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mux.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c9ef5290b8300cfedd91cce5e9d14d28)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/loraJam/mux.h>
// pydoc.h is automatically generated in the build directory
#include <mux_pydoc.h>

void bind_mux(py::module& m)
{

    using mux    = gr::loraJam::mux;


    py::class_<mux, gr::block, gr::basic_block,
        std::shared_ptr<mux>>(m, "mux", D(mux))

        .def(py::init(&mux::make),
           D(mux,make)
        )
        



        ;




}








