/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(payloadProcessing.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(698c1aa18a297b16f12288cf9a7fb36e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/loraJam/payloadProcessing.h>
// pydoc.h is automatically generated in the build directory
#include <payloadProcessing_pydoc.h>

void bind_payloadProcessing(py::module& m)
{

    using payloadProcessing    = gr::loraJam::payloadProcessing;


    py::class_<payloadProcessing, gr::block, gr::basic_block,
        std::shared_ptr<payloadProcessing>>(m, "payloadProcessing", D(payloadProcessing))

        .def(py::init(&payloadProcessing::make),
           D(payloadProcessing,make)
        )
        



        ;




}








