/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(trigger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(580ec0f92ec597d53c27b0770b0cae10)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/loraJam/trigger.h>
// pydoc.h is automatically generated in the build directory
#include <trigger_pydoc.h>

void bind_trigger(py::module& m)
{

    using trigger    = gr::loraJam::trigger;


    py::class_<trigger, gr::block, gr::basic_block,
        std::shared_ptr<trigger>>(m, "trigger", D(trigger))

        .def(py::init(&trigger::make),
           D(trigger,make)
        )
        



        ;




}








